spring:
  datasource:
    url: jdbc:mysql://${DB_URL:asdf}?characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME:adf}
    password: ${DB_PASSWORD:asdf}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    generate-ddl: true #spring.jpa.hibernate.ddl-auto 속성을 사용할지 말지, default = false
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true #hibernate가 db에 날리는 쿼리를 보여준다.
    properties:
      hibernate:
        format_sql: true #쿼리를 정리해서 보여준다.

  jackson:
    property-naming-strategy: SNAKE_CASE

jwt:
  secret-key: ${JWT_SECRET_KEY:asdf}
  access-exp: ${JWT_ACCESS_EXP:123456}

aws:
  s3:
    bucket: ${AWS_S3_BUCKET:bucket}
    shop-image-url: ${SHOP_IMAGE_URL:image/}
    item-image-url: ${ITEM_IMAGE_URL:image/}
    url: ${S3_BASE_URL:https://}

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: ${AWS_S3_ACCESS:s3_access}
      secret-key: ${AWS_S3_SECRET:s3_secret}